"""autovote - add phone number

Revision ID: 762693f1faba
Revises: c1259412a36c
Create Date: 2022-12-24 23:31:25.311518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762693f1faba'
down_revision = 'c1259412a36c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
